#!/usr/bin/env python3
"""Build the Codex skills and ChatGPT bundle from the first-party Claude skills."""

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / ".claude" / "skills"
TEMPLATES = Path(__file__).resolve().parent / "openai"
HELPERS = ("check-bib-usage.sh", "prune-unused-bib.sh", "merge-reports.py")
INPUT = (
    "Use the text, research notes, or file supplied with the user's request. "
    "If a file is named, read it using the available file tools. "
    "If no input is available, ask for the text or file instead of inventing it."
)


def read_skill(path):
    """Read the single-line metadata used by this repository's source skills."""
    frontmatter, body = path.read_text(encoding="utf-8").split("---\n", 2)[1:]
    metadata = {}
    for line in frontmatter.splitlines():
        key, separator, value = line.partition(":")
        if separator:
            metadata[key] = value.strip()
    return metadata, body.strip()


def portable_body(body):
    body = body.replace("provided in `$ARGUMENTS`", "provided by the user")
    body = body.replace("in `$ARGUMENTS`", "in the user's input")
    body = body.replace("# Input\n$ARGUMENTS", "# Input\n" + INPUT)
    return body


def build_outputs():
    outputs = {}
    sections = []
    # A local Claude install can add upstream skills beside our source skills.
    external = {"humanize-sk", "no-ai-slop"}
    sources = sorted(path for path in SOURCE.glob("*/SKILL.md") if path.parent.name not in external)
    names = []
    for source in sources:
        metadata, body = read_skill(source)
        name = metadata["name"]
        names.append(name)
        description = metadata["description"]
        body = portable_body(body)
        if name in {"finalize", "validate-bib"}:
            body = (TEMPLATES / (name + ".md")).read_text(encoding="utf-8").strip()
        if name == "validate-bib":
            description = (
                "Verify BibTeX entries against canonical web sources, annotate verdicts, "
                "and check unused or undefined citations. Use when asked to validate, "
                "verify, audit, or check a bibliography. Prune unused entries only on request."
            )

        description_yaml = json.dumps(description, ensure_ascii=False)
        header = f"---\nname: {name}\ndescription: {description_yaml}\n---\n\n"
        directory = Path("codex/skills") / name
        native_body = body
        if name == "finalize":
            native_body = native_body.replace(
                "Read the `logic-check`, `polish`, and `de-ai` definitions from this bundle.",
                "Read [logic-check](../logic-check/SKILL.md), [polish](../polish/SKILL.md), "
                "and [de-ai](../de-ai/SKILL.md) relative to this skill folder.",
            )
        if name == "validate-bib":
            native_body += "\n\n" + (TEMPLATES / "validate-bib-local.md").read_text(encoding="utf-8").strip()
            for helper in HELPERS:
                outputs[directory / helper] = (source.parent / helper).read_bytes()
        outputs[directory / "SKILL.md"] = (header + native_body + "\n").encode("utf-8")
        implicit = metadata.get("disable-model-invocation") != "true"
        outputs[directory / "agents/openai.yaml"] = (
            "policy:\n  allow_implicit_invocation: " + str(implicit).lower() + "\n"
        ).encode("utf-8")

        # Nest the original headings under each named skill in the upload bundle.
        body = re.sub(r"^(#+) ", r"##\1 ", body, flags=re.MULTILINE)
        sections.append("## Skill: " + name + "\n\n" + description + "\n\n" + body)

    intro = (
        "# Research writing skills for ChatGPT\n\n"
        "Apply only the skill requested by the user to their supplied text or files. "
        "The definitions below are independent workflows, except that `finalize` "
        "runs `logic-check`, `polish`, and `de-ai` in that order. Follow the selected "
        "skill's output format. Skill names in messages are plain-text selectors.\n\n"
        "Use only tools actually available in the current chat. If local file access "
        "is unavailable, work from pasted text or uploads and return the result in "
        "the reply or as a downloadable file. Never claim to have edited a local "
        "file, run a script, or verified a source without doing so.\n\n"
        "Available skills: " + ", ".join("`" + name + "`" for name in names) + ".\n\n"
        "<!-- Generated by scripts/build_openai.py; edit the source skills or scripts/openai templates. -->\n\n"
    )
    outputs[Path("chatgpt/research-writing.md")] = (intro + "\n\n---\n\n".join(sections) + "\n").encode("utf-8")
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if committed OpenAI artifacts are out of date")
    args = parser.parse_args()
    stale = []
    outputs = build_outputs()
    for relative, content in outputs.items():
        path = ROOT / relative
        if args.check:
            if not path.is_file() or path.read_bytes() != content:
                stale.append(str(relative))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
            if path.suffix == ".sh":
                path.chmod(0o755)
    if stale:
        parser.exit(1, "Out-of-date artifacts; run python3 scripts/build_openai.py:\n" + "\n".join(stale) + "\n")
    print(("Checked" if args.check else "Built") + " " + str(len(outputs)) + " OpenAI artifacts.")


if __name__ == "__main__":
    main()
